# Generated by Django 4.0.3 on 2022-04-03 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rateMySchoolApp', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcontent', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('upvoteCount', models.IntegerField(default=0)),
                ('downvoteCount', models.IntegerField(default=0)),
                ('rate_stars', models.IntegerField(default=0)),
                ('ratedBody', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rateMySchoolApp.universities')),
                ('raterUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
