# Generated by Django 4.0.3 on 2022-04-17 20:52

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('rateMySchoolApp', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='postcontent',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default=sqlalchemy.sql.expression.null),
        ),
    ]
