# Generated by Django 4.0.3 on 2022-04-18 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rateMySchoolApp', '0006_post_reporeted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='reporeted',
            new_name='reported',
        ),
    ]
