# Generated by Django 4.0.3 on 2022-04-18 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateMySchoolApp', '0007_rename_reporeted_post_reported'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reportedCount',
            field=models.BooleanField(default=0),
        ),
    ]
