# Generated by Django 4.0.3 on 2022-04-18 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateMySchoolApp', '0008_post_reportedcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reportedCount',
            field=models.IntegerField(default=0),
        ),
    ]
