# Generated by Django 4.0.3 on 2022-04-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateMySchoolApp', '0009_alter_post_reportedcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postreportedUsers',
            field=models.ManyToManyField(to='rateMySchoolApp.profile'),
        ),
    ]
