# Generated by Django 4.0.3 on 2022-04-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateMySchoolApp', '0010_post_postreportedusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
