# Generated by Django 4.0.3 on 2022-04-22 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateMySchoolApp', '0011_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postreportedUsers',
            field=models.ManyToManyField(blank=True, null=True, to='rateMySchoolApp.profile'),
        ),
    ]
