# Generated by Django 4.0.3 on 2022-04-23 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateMySchoolApp', '0013_post_downvote_post_upvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='auto_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='downvote',
            field=models.ManyToManyField(related_name='downvote', to='rateMySchoolApp.profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postreportedUsers',
            field=models.ManyToManyField(to='rateMySchoolApp.profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='upvote',
            field=models.ManyToManyField(related_name='upvote', to='rateMySchoolApp.profile'),
        ),
    ]
