# Generated by Django 4.0.3 on 2022-04-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateMySchoolApp', '0014_post_auto_reported_post_removed_alter_post_downvote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profanity_prob',
            field=models.FloatField(default=0),
        ),
    ]
