# Generated by Django 4.0.3 on 2022-05-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateMySchoolApp', '0016_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='Bio',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
