# Generated by Django 4.0.3 on 2022-05-06 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateMySchoolApp', '0017_professor_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='Bio',
        ),
        migrations.AddField(
            model_name='professor',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
