# Generated by Django 4.0.3 on 2022-05-06 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rateMySchoolApp', '0018_remove_professor_bio_professor_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostProfFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcontent', models.TextField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_last_edited', models.DateTimeField(auto_now=True)),
                ('edited', models.BooleanField(default=False)),
                ('reported', models.BooleanField(default=False)),
                ('post_type', models.CharField(blank=True, max_length=50, null=True)),
                ('reportedCount', models.IntegerField(default=0)),
                ('upvoteCount', models.IntegerField(default=0)),
                ('downvoteCount', models.IntegerField(default=0)),
                ('rate_stars', models.IntegerField(default=0)),
                ('auto_reported', models.BooleanField(default=False)),
                ('removed', models.BooleanField(default=False)),
                ('profanity_prob', models.FloatField(default=0)),
                ('downvote', models.ManyToManyField(related_name='profpostdownvote', to='rateMySchoolApp.profile')),
                ('postreportedUsers', models.ManyToManyField(to='rateMySchoolApp.profile')),
                ('ratedProf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rateMySchoolApp.professor')),
                ('raterUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('upvote', models.ManyToManyField(related_name='profpostupvote', to='rateMySchoolApp.profile')),
            ],
        ),
    ]
